{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailover"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKFailoverListener\/FailoverHandler","preciseIdentifier":"s:8MoneyKit18MKFailoverListenerC15FailoverHandlera","text":"FailoverHandler"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/moneykit\/mkfailoverlistener\/onfailover"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKFailoverListener\/onFailover","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The closure called when there is a failover scenario"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailover"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FailoverHandler","preciseIdentifier":"s:8MoneyKit18MKFailoverListenerC15FailoverHandlera"},{"kind":"text","text":"?"}],"title":"onFailover","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:8MoneyKit18MKFailoverListenerC10onFailoveryAA0C5EventVcSgvp","modules":[{"name":"MoneyKit"}]},"hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKFailoverListener"]]},"references":{"doc://com.moneykit.link/documentation/MoneyKit/MKFailoverListener":{"role":"symbol","title":"MKFailoverListener","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKFailoverListener"}],"abstract":[],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKFailoverListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MKFailoverListener"}],"url":"\/documentation\/moneykit\/mkfailoverlistener"},"doc://com.moneykit.link/documentation/MoneyKit/MKFailoverListener/onFailover":{"role":"symbol","title":"onFailover","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailover"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FailoverHandler","preciseIdentifier":"s:8MoneyKit18MKFailoverListenerC15FailoverHandlera"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The closure called when there is a failover scenario"}],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKFailoverListener\/onFailover","kind":"symbol","type":"topic","url":"\/documentation\/moneykit\/mkfailoverlistener\/onfailover"},"doc://com.moneykit.link/documentation/MoneyKit/MKFailoverListener/FailoverHandler":{"role":"symbol","title":"MKFailoverListener.FailoverHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailoverHandler"}],"abstract":[{"type":"text","text":"A closure that is called to indicate that a failover to MoneyKit is available."},{"type":"text","text":" "},{"type":"text","text":"The"},{"type":"codeVoice","code":"MKFailoverEvent"},{"type":"text","text":" arguement can be used to launch the MoneyKit SDK."}],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKFailoverListener\/FailoverHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FailoverHandler"}],"url":"\/documentation\/moneykit\/mkfailoverlistener\/failoverhandler"},"doc://com.moneykit.link/documentation/MoneyKit":{"role":"collection","title":"MoneyKit","abstract":[{"type":"text","text":"Internet Money Magic"}],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","kind":"symbol","type":"topic","url":"\/documentation\/moneykit"}}}